---
title: "final_project_cs3779"
author: "CJ Snyder"
date: "11/27/2019"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(rvest)
library(httr)
library(lubridate)
library(plotly)
library(rgdal)
library(sp)
library(sf)
library(leaflet)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

```{r, message=FALSE}
# Read in data
stop_frisk_df = 
  # Read in data from internet
  GET("https://www1.nyc.gov/assets/nypd/downloads/excel/analysis_and_planning/stop-question-frisk/sqf-2016.csv") %>% 
  content("parsed") %>% 
  
  # Clean and fix names of columns
  janitor::clean_names() %>% 
  rename(
    precinct = pct,
    date_stop = datestop,
    time_stop = timestop,
    stop_in_out = inout,
    obs_time_min = perobs,
    stop_time_min = perstop,
    arst_made = arstmade,
    off_in_unif = offunif,
    hair_col = haircolr,
    eye_col = eyecolor,
    other_feature = othfeatr,
    boro = city
  )  %>% 
  mutate(
    # Combine height columns
    height_inch = ht_feet * 12 + ht_inch,
    # Convert date to proper format
    date_stop = mdy(date_stop),
    # Convert time to proper format
    time_stop = hm(time_stop / 100),
    # Recode to be more informative
    stop_in_out = recode(stop_in_out, "I" = "inside", "O" = "outside"),
    race = recode(
      race, 
      "A" = "asian/pacific islander", 
      "B" = "black", 
      "I" = "american indian/alaska native",
      "P" = "black-hispanic",
      "Q" = "white-hispanic",
      "W" = "white",
      "U" = "unknown",
      "Z" = "other"
    ),
    hair_col = recode(
      hair_col,
      "BA" = "bald",
      "BK" = "black",
      "BL" = "blond",
      "BR" = "brown",
      "DY" = "dyed",
      "FR" = "frosted",
      "GY" = "gray",
      "RA" = "red",
      "SN" = "sandy",
      "SP" = "salt and pepper",
      "WH" = "white",
      "XX" = "unknown",
      "ZZ" = "other",
    ),
    eye_col = recode(
      eye_col,
      "BK" = "black",
      "BL" = "blue",
      "BR" = "brown",
      "DF" = "different",
      "GR" = "green",
      "GY" = "gray",
      "HA" = "hazel",
      "MA" = "maroon",
      "PK" = "pink",
      "VI" = "violet",
      "XX" = "unknown",
      "Z" = "other",      
    ),
    build = recode(
      build,
      "H" = "heavy",
      "M" = "medium",
      "T" = "thin",
      "U" = "muscular",
      "Z" = "unknown"
    ),
    # change boro columns to lowercase for consistency
    boro = tolower(boro),
    # change character datatypes to numeric
    age = as.numeric(age),
    obs_time_min = as.numeric(obs_time_min),
    stop_time_min = as.numeric(stop_time_min)
  )  %>% 
  # select columns for further analysis
  select(precinct, date_stop, time_stop, stop_in_out, obs_time_min, stop_time_min, arst_made, off_in_unif, frisked, 
         searched, rf_vcrim, rf_othsw, rf_attir:ac_evasv, cs_furtv:cs_other, rf_knowl, sb_hdobj:sb_admis, rf_furt, 
         rf_bulg, sex, race, age, height_inch, weight:other_feature, boro, xcoord, ycoord) %>% 
  # change all columns that have Y/N to 1/0
  mutate_at(vars(arst_made:rf_bulg), funs(recode(., "Y" = "1", "N" = "0"))) %>% 
  # change binary columns to numeric instead of character
  mutate_at(vars(arst_made:rf_bulg), funs(as.numeric(.))) %>% 
  # converts all character variables to factors (this does the same as the for loop)
  mutate_if(is.character, as.factor)
```


## Converting X Y Coordinates
```{r}
test_df= 
  stop_frisk_df %>% 
  select(xcoord, ycoord) %>% 
  drop_na()

coordinates(test_df) <- c("xcoord","ycoord")
proj4string(test_df) <- CRS("+init=epsg:2263")
CRS.new <- CRS("+init=epsg:4326") 
test_df_new <- spTransform(test_df, CRS.new)
test_df_new <- data.frame(longitude = coordinates(test_df_new)[,1], latitude = coordinates(test_df_new)[,2])
```



# Adding Precinct Data & Converting X/Y Coords
```{r}
nypd_prec = 
  st_read("./data/nypp/geo_export_55605c77-3922-4b7a-bd65-18d11225a91f.shp")

long_lat_df =
  stop_frisk_df %>% 
  select(xcoord, ycoord) %>% 
  drop_na()

coordinates(long_lat_df) <- c("xcoord", "ycoord")
proj4string(long_lat_df) <- CRS("+init=epsg:2263")
long_lat_df <- spTransform(long_lat_df, CRS("+init=epsg:4326"))
long_lat_df <- data.frame(longitude = coordinates(long_lat_df)[,1], latitude = coordinates(long_lat_df)[,2])

stop_frisk_map_df = 
  stop_frisk_df %>% 
  drop_na(xcoord) %>% 
  bind_cols(long_lat_df) %>% 
  select(-xcoord, -ycoord) %>% 
  mutate(
    sex = recode(sex, "M" = "male", "F" = "female"),
    label = str_c("Gender: ", sex, "<br/>", "Race: ", race) %>% map(htmltools::HTML)
  )
```

# Creating Maps
```{r, warning=FALSE}
# Locations of Stops
stop_frisk_map_df %>% 
  leaflet() %>% 
  addTiles() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addCircleMarkers(
    ~longitude, ~latitude,
    radius = 1,
    opacity = 0.6,
    label = ~label)

# Locations of Frisks
stop_frisk_map_df %>% 
  filter(frisked==1) %>% 
  leaflet() %>% 
  addTiles() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addCircleMarkers(
    ~longitude, ~latitude,
    radius = 1,
    opacity = 0.6,
    label = ~label)

# Locations of Stops with Precincts Outlines
stop_frisk_map_df %>% 
  leaflet() %>% 
  addTiles() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addCircleMarkers(
    ~longitude, ~latitude,
    radius = 1,
    opacity = 0.6,
    label = ~label) %>% 
  addPolygons(data = nypd_prec,
              color = "#000000",
              fillColor = "#FFFFFF",
              weight = 1,
              smoothFactor = 0.5,
              opacity = 1,
              fillOpacity = 0.1)

# Locations of Frisks with Precincts Outlines
stop_frisk_map_df %>% 
  filter(frisked==1) %>% 
  leaflet() %>% 
  addTiles() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addCircleMarkers(
    ~longitude, ~latitude,
    radius = 1,
    opacity = 0.6,
    label = ~label) %>% 
  addPolygons(data = nypd_prec,
              color = "#000000",
              fillColor = "#FFFFFF",
              weight = 1,
              smoothFactor = 0.5,
              opacity = 1,
              fillOpacity = 0.1)

# Colored Area based on Number of Stops with Information on # of Frisks by Precinct
stops_by_prec = 
  stop_frisk_df %>% 
  group_by(precinct) %>% 
  summarize(totalstops = n()) %>% 
  drop_na()

frisks_by_prec = 
  stop_frisk_df %>% 
  group_by(precinct) %>% 
  filter(frisked==1) %>% 
  summarize(totalfrisks = n())

nypd_prec  = 
  inner_join(nypd_prec, stops_by_prec, by="precinct") %>% 
  inner_join(., frisks_by_prec, by="precinct")

pal <- colorNumeric("YlOrRd", domain = range(nypd_prec$totalstops))
pal2 <- colorNumeric("YlOrRd", domain = range(nypd_prec$totalfrisks))

nypd_prec =
nypd_prec %>% 
  mutate(
    tsc = pal(totalstops),
    tfc = pal2(totalfrisks),
    label = str_c("Precinct: ", precinct, "<br/>", "Total Stops in 2016: ", totalstops, "<br/>", "Total Frisks in 2016: ", totalfrisks) %>% map(htmltools::HTML)
  )

# Total Stops by Precinct
nypd_prec %>% 
  leaflet() %>% 
  addTiles() %>%
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addPolygons(label = ~label,
              color = "#000000",
              fillColor = ~tsc,
              weight = 1,
              smoothFactor = 0.5,
              opacity = 1,
              fillOpacity = 0.5,
              highlightOptions = highlightOptions(color = "white",
                                                  weight = 2,
                                                  bringToFront = TRUE)) %>% 
  addLegend(pal = pal,
            values = ~totalstops,
            title = "Total Number of Stops",
            position = "bottomright")

# Total Frisks by Precinct
nypd_prec %>% 
  leaflet() %>% 
  addTiles() %>%
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addPolygons(label = ~label,
              color = "#000000",
              fillColor = ~tfc,
              weight = 1,
              smoothFactor = 0.5,
              opacity = 1,
              fillOpacity = 0.5,
              highlightOptions = highlightOptions(color = "white",
                                                  weight = 2,
                                                  bringToFront = TRUE)) %>% 
  addLegend(pal = pal2,
            values = ~totalfrisks,
            title = "Total Number of Frisks",
            position = "bottomright")
```


# Combining to Try Layering Functioning (but this can be accomplished with Shiny as well)
```{r}
stop_frisk_map_df %>% 
  leaflet() %>% 
  addTiles() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addPolygons(data = nypd_prec,
              label = ~label,
              color = "#000000",
              fillColor = ~tfc,
              weight = 1,
              smoothFactor = 0.5,
              opacity = 1,
              fillOpacity = 0.5,
              group = "Police Precincts"
  ) %>% 
  addLegend(data = nypd_prec,
            pal = pal,
            values = ~totalstops,
            title = "Total Number of Stops",
            position = "bottomright",
            group = "Police Precincts"
  ) %>% 
  addCircleMarkers(
    ~longitude, ~latitude,
    radius = 1,
    opacity = 0.6,
    group = "Individual Stops") %>% 
  addLayersControl(
    overlayGroups = c("Individual Stops", "Police Precincts"),
    options = layersControlOptions(collapsed = FALSE)
  )
```

# Showing Distribution of Stops by Race 
```{r}
stops_by_race = 
  left_join(stop_frisk_map_df, stops_by_prec, by="precinct") %>% 
  group_by(precinct, race) %>% 
  summarize(stops_by_race = n()) %>% 
  left_join(., stops_by_prec, by="precinct") %>% 
  mutate(
    percentstops = (stops_by_race/totalstops)*100
  ) 

pal3 <- colorFactor("YlOrRd", domain = stops_by_race$race)

max_stops_by_race = 
  stops_by_race %>% 
  group_by(precinct) %>% 
  top_n(1, percentstops) %>% 
  mutate(maxstoppedrace = race) %>% 
  select(precinct, maxstoppedrace)

nypd_prec = left_join(nypd_prec, max_stops_by_race, by="precinct")

nypd_prec %>% 
  leaflet() %>% 
  addTiles() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addPolygons(label = ~maxstoppedrace,
              color = "#000000",
              fillColor = ~pal3(maxstoppedrace),
              weight = 1,
              smoothFactor = 0.5,
              opacity = 1,
              fillOpacity = 0.5
  ) %>% 
   addLegend(pal = pal3,
            values = ~maxstoppedrace,
            title = "Race Making Up the Largest <br/>
            Percentage Stops",
            position = "bottomright")
```

