---
title: "Visualizations"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(rvest)
library(httr)
library(lubridate)
library(plotly)
library(rgdal)
library(sp)
library(sf)
library(leaflet)
library(patchwork)
```

```{r, include=FALSE}
# Read in data
stop_frisk_df = 
  # Read in data from internet
  GET("https://www1.nyc.gov/assets/nypd/downloads/excel/analysis_and_planning/stop-question-frisk/sqf-2016.csv") %>% 
  content("parsed") %>% 
  
  # Clean and fix names of columns
  janitor::clean_names() %>% 
  rename(
    precinct = pct,
    date_stop = datestop,
    time_stop = timestop,
    stop_in_out = inout,
    obs_time_min = perobs,
    stop_time_min = perstop,
    arst_made = arstmade,
    off_in_unif = offunif,
    hair_col = haircolr,
    eye_col = eyecolor,
    other_feature = othfeatr,
    boro = city
  )  %>% 
  mutate(
    # Combine height columns
    height_inch = ht_feet * 12 + ht_inch,
    # Convert date to proper format
    date_stop = mdy(date_stop),
    # Convert time to proper format
    time_stop = hm(time_stop / 100),
    # Recode to be more informative
    stop_in_out = recode(stop_in_out, "I" = "inside", "O" = "outside"),
    race = recode(
      race, 
      "A" = "other", 
      "B" = "black", 
      "I" = "other",
      "P" = "black-hispanic",
      "Q" = "white-hispanic",
      "W" = "white",
      "U" = "other",
      "Z" = "other"
    ),
    hair_col = recode(
      hair_col,
      "BA" = "bald",
      "BK" = "black",
      "BL" = "blond",
      "BR" = "brown",
      "DY" = "other",
      "FR" = "other",
      "GY" = "other",
      "RA" = "other",
      "SN" = "other",
      "SP" = "other",
      "WH" = "other",
      "XX" = "other",
      "ZZ" = "other",
    ),
    eye_col = recode(
      eye_col,
      "BK" = "black",
      "BL" = "blue",
      "BR" = "brown",
      "DF" = "other",
      "GR" = "other",
      "GY" = "other",
      "HA" = "other",
      "MA" = "other",
      "PK" = "other",
      "VI" = "other",
      "XX" = "other",
      "Z" = "other",      
    ),
    build = recode(
      build,
      "H" = "heavy",
      "M" = "medium",
      "T" = "thin",
      "U" = "other",
      "Z" = "unknown"
    ),
    # change boro columns to lowercase for consistency
    boro = tolower(boro),
    # change character datatypes to numeric
    age = as.numeric(age),
    obs_time_min = as.numeric(obs_time_min),
    stop_time_min = as.numeric(stop_time_min)
  )  %>% 
  # select columns for further analysis
  select(precinct, date_stop, time_stop, stop_in_out, obs_time_min, stop_time_min, arst_made, off_in_unif, frisked, 
         searched, rf_vcrim, rf_othsw, rf_attir:ac_evasv, cs_furtv:cs_other, rf_knowl, sb_hdobj:sb_admis, rf_furt, 
         rf_bulg, sex, race, age, height_inch, weight:build, boro, xcoord, ycoord) %>% 
  # change all columns that have Y/N to 1/0
  mutate_at(vars(arst_made:rf_bulg), funs(recode(., "Y" = "1", "N" = "0"))) %>% 
  # change binary columns to numeric instead of character
  mutate_at(vars(arst_made:rf_bulg), funs(as.numeric(.))) %>% 
  # converts all character variables to factors (this does the same as the for loop)
  mutate_if(is.character, as.factor) %>% 
  # remove the single row of NAs
  filter(!is.na(build))
```



Column {data-width=500}
-----------------------------------------------------------------------

### Percentage of Reported Stops and Frisks by Race 

```{r}
stop =
  stop_frisk_df %>% 
  drop_na() %>% 
  mutate(
    race = fct_infreq(race)
    ) %>% 
  ggplot(aes(race, fill = race))+
  geom_bar(aes(y=(..count..)/sum(..count..)),alpha = .5, position = "dodge")+
  labs(
    title = "Percentages of Reported Stops by Race",
    y= "percentage") +
    theme(legend.position = "none")

frisk =
  stop_frisk_df %>% 
  drop_na() %>% 
  mutate(
    race = fct_infreq(race)
    ) %>% 
  filter(frisked == '1') %>% 
  ggplot(aes(race, fill = race))+
  geom_bar(aes(y=(..count..)/sum(..count..)),alpha = .5, position = "dodge")+
  labs(
    title = "Percentages of Reported Stops Resulting in a Frisk by Race",
    y= "percentage") +
    theme(legend.position = "none")

(stop/frisk)
```


Column {data-width=450}
-----------------------------------------------------------------------

### Distribution of Age by Race

```{r}
p = stop_frisk_df %>% 
drop_na() %>% 
mutate(stopped = as.numeric(stop_in_out),
stopped = case_when(
stopped > 0 ~ '1',
TRUE ~""),
stopped = as.numeric(stopped)) %>% 
select(age, arst_made, frisked, stopped) %>% 
pivot_longer(
arst_made:stopped,
names_to = "action",
values_to = "value") %>% 
filter(value == '1') %>% 
count(age, action) %>% 
 ggplot(aes(y= age, x  = action )) +
   geom_boxplot(aes(color=action), alpha = .4)
ggplotly(p)
  
```

### Total Count of Frisked, Searched, and Arrested of Subjects by Race and Sex 

```{r}

frisked_plot = 
  stop_frisk_df %>% 
  drop_na() %>% 
  mutate(
    race = fct_infreq(race)
    ) %>% 
  filter( 
    frisked == '1') %>% 
  ggplot(aes(x = race, fill = sex))+
  geom_bar(alpha = .5, position = "dodge")+
  labs(
    title = "Frisked")+
  theme(axis.text.x = element_text(angle = 80, hjust = 1))

# subjects count of searched subjects by race, sex
searched_plot = 
  stop_frisk_df  %>% 
  drop_na() %>% 
  mutate(
    race = fct_infreq(race)) %>% 
  filter(searched =='1') %>% 
  ggplot(aes(x = race, fill = sex))+
  geom_bar(alpha = .5, position = "dodge")+
  labs(
    title = "Searched")+
  theme(axis.text.x = element_text(angle = 80, hjust = 1))

# subjects count of arrested subjects by race, sex
arrested_plot = 
  stop_frisk_df  %>% 
  drop_na() %>% 
  mutate(
    race = fct_infreq(race)) %>% 
  filter(arst_made =='1') %>% 
  ggplot(aes(x = race, fill = sex))+
  geom_bar(alpha = .5, position = "dodge")+
  labs(
    title = "Arrested")+
  theme(axis.text.x = element_text(angle = 80, hjust = 1))


(frisked_plot + searched_plot + arrested_plot)
```

