---
title: "total_stops"
author: "kd2640_total_stops"
date: '`r format(Sys.time(), "%Y-%m-%d")`'
output: html_document
---




```{r setup, include=FALSE}

library(tidyverse)
library(viridis)
library(rvest)
library(httr)
library(lubridate)
library(plotly)
library(caret)
library(ROCR)
library(Metrics)
library(glmnet)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```



```{r, message=FALSE, include=FALSE}
# Read in data
stop_frisk_df = 
  # Read in data from internet
  GET("https://www1.nyc.gov/assets/nypd/downloads/excel/analysis_and_planning/stop-question-frisk/sqf-2016.csv") %>% 
  content("parsed") %>% 
  
  # Clean and fix names of columns
  janitor::clean_names() %>% 
  rename(
    precinct = pct,
    date_stop = datestop,
    time_stop = timestop,
    stop_in_out = inout,
    obs_time_min = perobs,
    stop_time_min = perstop,
    arst_made = arstmade,
    off_in_unif = offunif,
    hair_col = haircolr,
    eye_col = eyecolor,
    other_feature = othfeatr,
    boro = city
  )  %>% 
  mutate(
    # Combine height columns
    height_inch = ht_feet * 12 + ht_inch,
    # Convert date to proper format
    date_stop = mdy(date_stop),
    # Convert time to proper format
    time_stop = hm(time_stop / 100),
    # Recode to be more informative
    stop_in_out = recode(stop_in_out, "I" = "inside", "O" = "outside"),
    race = recode(
      race, 
      "A" = "asian/pacific islander", 
      "B" = "black", 
      "I" = "american indian/alaska native",
      "P" = "black-hispanic",
      "Q" = "white-hispanic",
      "W" = "white",
      "U" = "unknown",
      "Z" = "other"
    ),
    hair_col = recode(
      hair_col,
      "BA" = "bald",
      "BK" = "black",
      "BL" = "blond",
      "BR" = "brown",
      "DY" = "dyed",
      "FR" = "frosted",
      "GY" = "gray",
      "RA" = "red",
      "SN" = "sandy",
      "SP" = "salt and pepper",
      "WH" = "white",
      "XX" = "unknown",
      "ZZ" = "other",
    ),
    eye_col = recode(
      eye_col,
      "BK" = "black",
      "BL" = "blue",
      "BR" = "brown",
      "DF" = "different",
      "GR" = "green",
      "GY" = "gray",
      "HA" = "hazel",
      "MA" = "maroon",
      "PK" = "pink",
      "VI" = "violet",
      "XX" = "unknown",
      "Z" = "other",      
    ),
    build = recode(
      build,
      "H" = "heavy",
      "M" = "medium",
      "T" = "thin",
      "U" = "muscular",
      "Z" = "unknown"
    ),
    # change boro columns to lowercase for consistency
    boro = tolower(boro),
    # change character datatypes to numeric
    age = as.numeric(age),
    obs_time_min = as.numeric(obs_time_min),
    stop_time_min = as.numeric(stop_time_min)
  )  %>% 
  # select columns for further analysis
  select(precinct, date_stop, time_stop, stop_in_out, obs_time_min, stop_time_min, arst_made, off_in_unif, frisked, 
         searched, rf_vcrim, rf_othsw, rf_attir:ac_evasv, cs_furtv:cs_other, rf_knowl, sb_hdobj:sb_admis, rf_furt, 
         rf_bulg, sex, race, age, height_inch, weight:build, boro, xcoord, ycoord) %>% 
  # change all columns that have Y/N to 1/0
  mutate_at(vars(arst_made:rf_bulg), funs(recode(., "Y" = "1", "N" = "0"))) %>% 
  # change binary columns to numeric instead of character
  mutate_at(vars(arst_made:rf_bulg), funs(as.numeric(.))) %>% 
  # converts all character variables to factors (this does the same as the for loop)
  mutate_if(is.character, as.factor) %>% 
  # remove the single row of NAs
  filter(!is.na(build))
```





Comparing the reason why people were stopped 

```{r, eval=FALSE}
frisks_total =
stop_frisk_df %>% 
  select(cs_objcs:cs_lkout, cs_cloth, cs_drgtr, cs_furtv, cs_vcrim:cs_other) %>% 
  pivot_longer(
    cs_objcs:cs_other,
    names_to = "reason_stopped",
    values_to = "stops"
  ) %>% 
  mutate(
    reason_stopped = recode(
    reason_stopped,
    "cs_objcs" = "carrying suspicious object",
    "cs_descr" = "fits a relevant description",
    "cs_casng" = "casing a victim or location",
    "cs_lkout" = "suspect acting as a lookout",
    "cs_cloth" = "wearing clothes commonly used in crimes",
    "cs_drgtr" = "actions indicative of drug transaction",
    "cs_furtv" = "furtive movements",
    "cs_vcrim" = "actions engaging in violent crime",
    "cs_bulge" = "suspcious bulge",
    "cs_other" = "other"
  )) %>% 
  filter(stops == 1) %>% 
  group_by(reason_stopped) %>% 
  summarize(total =n()) %>% 
  mutate(prob = total/sum(total)) 

stops_total %>% 
  plot_ly(x = ~reason_stopped, y= ~total, type = "bar" , color = ~reason_stopped)

stops_total %>% 
 plot_ly(x = ~reason_stopped, y= ~prob, type = "bar" , color = ~reason_stopped) 
  
```


total stops by ages

```{r, eval=FALSE}
stops_by_age = 
stop_frisk_df %>% 
  select(cs_objcs:cs_lkout, cs_cloth, cs_drgtr, cs_furtv, cs_vcrim:cs_other, age) %>% 
  pivot_longer(
    cs_objcs:cs_other,
    names_to = "reason_stopped",
    values_to = "stops"
  ) %>% mutate(
    reason_stopped = recode(
    reason_stopped,
    "cs_objcs" = "carrying suspicious object",
    "cs_descr" = "fits a relevant description",
    "cs_casng" = "casing a victim or location",
    "cs_lkout" = "suspect acting as a lookout",
    "cs_cloth" = "wearing clothes commonly used in crimes",
    "cs_drgtr" = "actions indicative of drug transaction",
    "cs_furtv" = "furtive movements",
    "cs_vcrim" = "actions engaging in violent crime",
    "cs_bulge" = "suspcious bulge",
    "cs_other" = "other"
  )) %>% 
  filter(stops == 1) %>% 
  group_by(reason_stopped, age) %>% 
  summarize(total =n()) %>% 
  mutate(prob = total/sum(total)) 

stops_by_age %>% 
  plot_ly(x = ~age, y= ~prob, type = "bar" , color = ~reason_stopped)

stops_by_age %>% 
  plot_ly(x = ~age, y= ~total, type = "bar" , color = ~reason_stopped)
```


total stop by age group 

```{r, eval=FALSE}
stop_age_group  =
  stop_frisk_df %>% 
  select(cs_objcs:cs_lkout, cs_cloth, cs_drgtr, cs_furtv, cs_vcrim:cs_other,age) %>% 
  mutate(
    age_group = case_when(
      age < '18' ~ "18-",
      age >= '18' & age < '30' ~ "18-30",
      age >= '30' & age < '40' ~ "30s",
      age >= '40' & age < '50' ~ "40s",
      age >= '50' & age < '60' ~ "50s",
      age >= '60' ~"60+"
    )
    ) %>% 
   pivot_longer(
    cs_objcs:cs_other,
    names_to = "reason_stopped",
    values_to = "stops"
  ) %>% 
  mutate(
    reason_stopped = recode(
    reason_stopped,
    "cs_objcs" = "carrying suspicious object",
    "cs_descr" = "fits a relevant description",
    "cs_casng" = "casing a victim or location",
    "cs_lkout" = "suspect acting as a lookout",
    "cs_cloth" = "wearing clothes commonly used in crimes",
    "cs_drgtr" = "actions indicative of drug transaction",
    "cs_furtv" = "furtive movements",
    "cs_vcrim" = "actions engaging in violent crime",
    "cs_bulge" = "suspcious bulge",
    "cs_other" = "other"
  )) %>% 
  filter(stops == 1) %>% 
  group_by(reason_stopped, age_group) %>% 
  summarize(total =n()) %>% 
  mutate(prob = total/sum(total)) %>% 
  drop_na

stop_age_group %>% 
  plot_ly(x = ~age_group, y= ~prob, type = "bar" , color = ~reason_stopped) 


stop_age_group %>% 
 plot_ly(x = ~age_group, y= ~total, type = "bar" , color = ~reason_stopped) 
  
stop_age_group %>% 
  ggplot(aes(age_group, total, fill = age_group)) +
  geom_col() +
  transition_states(
    reason_stopped,
    transition_length = 3,
    state_length = 3
  ) +
  enter_fade() +
  exit_shrink() +
  ggtitle('{closest_state}')
```

total stops by sex 

```{r, eval=FALSE}
stops_by_sex = 
  stop_frisk_df %>% 
  select(cs_objcs:cs_lkout, cs_cloth, cs_drgtr, cs_furtv, cs_vcrim:cs_other, sex) %>% 
  pivot_longer(
    cs_objcs:cs_other,
    names_to = "reason_stopped",
    values_to = "stops"
  ) %>% 
   mutate(
     sex = recode(
    sex,
    "F" = "female",
    "M" = "male",
    "Z" = "other"
  ), 
  reason_stopped = recode(
    reason_stopped,
    "cs_objcs" = "carrying suspicious object",
    "cs_descr" = "fits a relevant description",
    "cs_casng" = "casing a victim or location",
    "cs_lkout" = "suspect acting as a lookout",
    "cs_cloth" = "wearing clothes commonly used in crimes",
    "cs_drgtr" = "actions indicative of drug transaction",
    "cs_furtv" = "furtive movements",
    "cs_vcrim" = "actions engaging in violent crime",
    "cs_bulge" = "suspcious bulge",
    "cs_other" = "other"
  )) %>% 
   filter(stops == 1) %>% 
  group_by(reason_stopped, sex) %>% 
  summarize(total =n()) %>%
  mutate(prop = total/sum(total)) 

stops_by_sex %>% 
  plot_ly(x = ~sex, y= ~prop, type = "bar" , color = ~reason_stopped)

stops_by_sex %>% 
  plot_ly(x = ~sex, y = ~total, type = "bar", color = ~reason_stopped)
```

total stops by race

```{r, eval=FALSE}
stop_by_race = 
  stop_frisk_df %>% 
  select(cs_objcs:cs_lkout, cs_cloth, cs_drgtr, cs_furtv, cs_vcrim:cs_other, race) %>% 
  pivot_longer(
    cs_objcs:cs_other,
    names_to = "reason_stopped",
    values_to = "stops"
  ) %>% mutate(
    reason_stopped = recode(
    reason_stopped,
    "cs_objcs" = "carrying suspicious object",
    "cs_descr" = "fits a relevant description",
    "cs_casng" = "casing a victim or location",
    "cs_lkout" = "suspect acting as a lookout",
    "cs_cloth" = "wearing clothes commonly used in crimes",
    "cs_drgtr" = "actions indicative of drug transaction",
    "cs_furtv" = "furtive movements",
    "cs_vcrim" = "actions engaging in violent crime",
    "cs_bulge" = "suspcious bulge",
    "cs_other" = "other"
  )) %>% 
   filter(stops == 1) %>% 
  group_by(reason_stopped, race) %>% 
  summarize(total =n()) %>% 
  mutate(prop = total/sum(total)) 

stop_by_race %>% 
  plot_ly(x = ~race, y= ~prop, type = "bar" , color = ~reason_stopped)

stop_by_race %>% 
  plot_ly(x = ~race, y= ~total, type = "bar" , color = ~reason_stopped)
```


total stops by date

```{r, eval=FALSE}
stops_by_month =
stop_frisk_df %>% 
  select(cs_objcs:cs_lkout, cs_cloth, cs_drgtr, cs_furtv, cs_vcrim:cs_other, date_stop) %>% 
  mutate( month_stop = month(date_stop)) %>% 
  pivot_longer(
    cs_objcs:cs_other,
    names_to = "reason_stopped",
    values_to = "stops"
  ) %>% mutate(
    reason_stopped = recode(
    reason_stopped,
    "cs_objcs" = "carrying suspicious object",
    "cs_descr" = "fits a relevant description",
    "cs_casng" = "casing a victim or location",
    "cs_lkout" = "suspect acting as a lookout",
    "cs_cloth" = "wearing clothes commonly used in crimes",
    "cs_drgtr" = "actions indicative of drug transaction",
    "cs_furtv" = "furtive movements",
    "cs_vcrim" = "actions engaging in violent crime",
    "cs_bulge" = "suspcious bulge",
    "cs_other" = "other"
  )) %>% 
   filter(stops == 1) %>% 
  group_by(reason_stopped, month_stop) %>% 
  summarize(total =n()) %>% 
  mutate( prob = total/sum(total))

stops_by_month %>% 
  plot_ly(x = ~month_stop, y= ~total, type = "bar" , color = ~reason_stopped)

stops_by_month %>% 
  plot_ly(x = ~month_stop, y= ~prob, type = "bar" , color = ~reason_stopped)
```


total of stop by inside and outside 

```{r, eval=FALSE}
in_out_stops = 
stop_frisk_df %>% 
  select(cs_objcs:cs_lkout, cs_cloth, cs_drgtr, cs_furtv, cs_vcrim:cs_other, stop_in_out) %>% 
  pivot_longer(
    cs_objcs:cs_other,
    names_to = "reason_stopped",
    values_to = "stops"
  ) %>% mutate(
    reason_stopped = recode(
    reason_stopped,
    "cs_objcs" = "carrying suspicious object",
    "cs_descr" = "fits a relevant description",
    "cs_casng" = "casing a victim or location",
    "cs_lkout" = "suspect acting as a lookout",
    "cs_cloth" = "wearing clothes commonly used in crimes",
    "cs_drgtr" = "actions indicative of drug transaction",
    "cs_furtv" = "furtive movements",
    "cs_vcrim" = "actions engaging in violent crime",
    "cs_bulge" = "suspcious bulge",
    "cs_other" = "other"
  )) %>% 
   filter(stops == 1) %>% 
  group_by(reason_stopped, stop_in_out) %>% 
  summarize(total =n()) %>% 
  mutate( prob = total/sum(total))

in_out_stops %>% 
  plot_ly(x = ~stop_in_out, y= ~total, type = "bar" , color = ~reason_stopped)

in_out_stops %>% 
   plot_ly(x = ~stop_in_out, y= ~prob, type = "bar" , color = ~reason_stopped)
```


arrest made by total stops

```{r, eval=FALSE}
stops_arrest =
stop_frisk_df %>% 
  select(cs_objcs:cs_lkout, cs_cloth, cs_drgtr, cs_furtv, cs_vcrim:cs_other, arst_made) %>% 
  pivot_longer(
    cs_objcs:cs_other,
    names_to = "reason_stopped",
    values_to = "stops"
  ) %>% mutate(
    reason_stopped = recode(
    reason_stopped,
    "cs_objcs" = "carrying suspicious object",
    "cs_descr" = "fits a relevant description",
    "cs_casng" = "casing a victim or location",
    "cs_lkout" = "suspect acting as a lookout",
    "cs_cloth" = "wearing clothes commonly used in crimes",
    "cs_drgtr" = "actions indicative of drug transaction",
    "cs_furtv" = "furtive movements",
    "cs_vcrim" = "actions engaging in violent crime",
    "cs_bulge" = "suspcious bulge",
    "cs_other" = "other"
  )) %>% 
  mutate(
    arst_made = recode(
      arst_made,
      '0' = "not arrested",
      '1' = "arrested"
    )
  ) %>% 
   filter(stops == 1) %>% 
  group_by(reason_stopped, arst_made) %>% 
  summarize(total =n()) %>% 
  mutate( prob = total/sum(total))

stops_arrest %>% 
  plot_ly(x = ~arst_made, y= ~total, type = "bar" , color = ~reason_stopped)

stops_arrest %>% 
  plot_ly(x = ~arst_made, y= ~prob, type = "bar" , color = ~reason_stopped)
```

total stops by boro 

```{r, eval=FALSE}
stop_by_boro = 
  stop_frisk_df %>% 
  select(cs_objcs:cs_lkout, cs_cloth, cs_drgtr, cs_furtv, cs_vcrim:cs_other, boro) %>% 
  pivot_longer(
    cs_objcs:cs_other,
    names_to = "reason_stopped",
    values_to = "stops"
  ) %>% mutate(
    reason_stopped = recode(
    reason_stopped,
    "cs_objcs" = "carrying suspicious object",
    "cs_descr" = "fits a relevant description",
    "cs_casng" = "casing a victim or location",
    "cs_lkout" = "suspect acting as a lookout",
    "cs_cloth" = "wearing clothes commonly used in crimes",
    "cs_drgtr" = "actions indicative of drug transaction",
    "cs_furtv" = "furtive movements",
    "cs_vcrim" = "actions engaging in violent crime",
    "cs_bulge" = "suspcious bulge",
    "cs_other" = "other"
  )) %>% 
   filter(stops == 1) %>% 
  group_by(reason_stopped, boro) %>% 
  summarize(total =n()) %>% 
  mutate( prob = total/sum(total))

stop_by_boro %>% 
  plot_ly(x = ~boro, y= ~prob, type = "bar" , color = ~reason_stopped)

stop_by_boro %>% 
  plot_ly(x = ~boro, y= ~total, type = "bar" , color = ~reason_stopped)
```

```{r}
reason_stopped = 
  stop_frisk_df %>% 
  select(cs_objcs:cs_lkout, cs_cloth, cs_drgtr, cs_furtv, cs_vcrim:cs_other, frisked) %>% 
  pivot_longer(
    cs_objcs:cs_other,
    names_to = "reason_stopped",
    values_to = "stops"
  ) %>% 
  mutate(
    reason_stopped = recode(
    reason_stopped,
    "cs_objcs" = "carrying suspicious object",
    "cs_descr" = "fits a relevant description",
    "cs_casng" = "casing a victim or location",
    "cs_lkout" = "suspect acting as a lookout",
    "cs_cloth" = "wearing clothes commonly used in crimes",
    "cs_drgtr" = "actions indicative of drug transaction",
    "cs_furtv" = "furtive movements",
    "cs_vcrim" = "actions engaging in violent crime",
    "cs_bulge" = "suspicious bulge",
    "cs_other" = "other"
  )) %>% 
  filter(stops == 1) %>% 
  group_by(reason_stopped) %>% 
  summarize(total =n()) 

```

`r pull(reason_stopped, reason_stopped)`

```{r}
stop_frisk_df %>% 
  filter(frisked==1) %>% 
  count(frisked) 
 stop_frisk_df %>% 
   group_by(sex) %>% 
   summarize(n = n())
```

