---
title: "Stop! You are being frisked!"
author: "Lauren, Olya, Matt, Cj, & Keyanna"
date: "December 5, 2019"
output:
  html_document:
    toc: TRUE
    toc_float: TRUE
    code_folding: hide
      
---





# Motivation

Terry Stop is a crime-preventing program that has been used by the police around the country for more than 40 years. In New York City this program is known as stop-and-frisk and consists of possible temporary detention and questioning of an individual with possible searching for weapons or other contraband. During Michael Bloomberg’s tenure as a mayor of the City of New York, this program became increasingly aggressive and subsequently turned out to be the hot topic of discussion throughout the nation. In 2011 stop-and-frisk reached almost 700,000 stops. During the same year the New York Civil Liberties Union successfully sued the New York Police Department and forced it to regularly report to public all stop-and-frisk related activities. From the obtained data, it was concluded, that majority of stopped individuals were black and Hispanic men. Bloomberg and then NYC Police Commissioner Raymond W. Kelly, were accused of racial profiling. 

Stop-and-frisk has been proven to be unsuccessful in identifying criminals and recovering illegal weapons. For years Bloomberg argued that there is a causal relationship between stop-and-frisk and crime rates in NYC, in order to rally support for the program. This assumption has been proven to be incorrect by the fact that even after the program was scaled back, crime rates continued to decline in NYC. 
During mayoral election campaign in 2013, public pressure forced Bloomberg to cut back this  practice. 

After Bill de Blasio won mayoral election in 2013, he continued to downsize the program. In 2016 number of stops were less than 2% in comparison to that of 2011, when the stops reached its peak. In spite of expectations, crime prevalence continued to decline even after the program was decreased by 98%.  



# Related Work
New York Civil Liberties Union report “Stop-and-Frisk in the de Blasio era”.

*Provide an overview of the project goals and motivation*


# Related Work
*Anything that inspired you, such as a paper, a website, or something we discussed in class?*


# Initial Questions
*What questions are you trying to answer? How did these questions evolve over the course over the course of the project? What new questions did you consider in the course of your analysis?*

We are interested in determining if there is a predictive nature to this dataset. We also want to describe the scope of the dataset through visualizations of the different demographics present, reasons for stopping, and create a map of stops across the five boroughs. Specifically, we strive to answer the following questions:


* What is the distribution of demographics in the dataset? 
* After being stopped, can demographics, characteristics, and location of stop predict whether or not the individual will be frisked or arrested? 
* Are there any difference between stops made over the course of the year? Week? Time of day? 
* What are the trends in stops across different areas of New York City? 

# Data
Our dataset is from the New York Police Department and was obtained through the NYC Open Data resource. It contains data from 12,404 stops that occurred during 2016. The original dataset contained 112 variables, however to narrow our focus, the dataset was reduced down to 45 categorical, binary, and numerical variables that describe each stop and are relevant to the questions at hand. The data cleaning and tidying process recoded variables, implemented understandable variable names, and converted categorical variables to factors and binary variables into ‘0’ and ‘1’ within R. The outcome variables that we are interested in building models for are FRISKED and ARST_MADE. These variables are binary in nature and describe whether the stopped individual was frisked, and whether the individual was arrested. Below is the distribution of the data for both of these variables. The dataset contains __ individuals who were frisked (##%) , and ___ individuals who were arrested (##%).  


# Exploratory Analysis
*Visualizations, summaries, and exploratory statistical analyses. Justify the steps you took, and show any major changes to you ideas.*

## Logistic Regression Analysis

Goal: To select for models that will answer the following questions:

 * Among those who were stopped, can we model demographics, location of stop, and reasons for stopping to predict whether the person will be frisked or not?
 * Among those who were stopped, can we model demographics, location of stop, and reasons for stopping to predict whether the person will be arrested or not? 

Methods: 

To obtain a dataset that could be used to model logistic regression, several categorical variables with levels that had representation of less than 2% were regrouped into 'other' to ensure that both the testing and training dataset have individuals represented from all categorical levels. This included regrouping levels within the variables build, race, hair_col, and eye_color. Only variables that preceded the individual being stopped were used in logistic regression models. Thus, all variables that described reason for frisk or reason for search were omitted. We focused on the characteristics, demographics, location, and reasons for stopping in the model. To build models for ARST_MADE and FRISKED, we evaluated GVIF to verify that there is no multicollinearity present and removed any variables suspected of having high collinearity. Model selection was based on consideration of AIC values, inflated standard errors, and p values. When AIC values did not change between models, ANOVA was used to compare similar models to determine whether the larger or smaller model was significantly better. Above all, we wanted to keep the concept of parsimony in mind when selecting models and minimize overfitting. Finally, the models were evaluated using a training and testing dataset to assess the preditive ability of the model using Area Under the Curve (AUC). 

FRISKED Model: 

Utilizing the methods above, the logistic regression model that was determined to have the best predictive ability included the variables: sex, race, age, height, build, stop inside/outside, officer in uniform, precinct, reason for stop - fits a relevant description, casing a victim or location, furtive movements, violent crime suspected, suspicious bulge, and other. With this model, the predictive power was 0.566. This value is only slightly better than guessing (0.50).

ARST_MADE Model: 

The logistic regression model that was determined to have the best predictive ability included the variables: sex, race, weight, stop inside/outside, precinct, officer in uniform, and hair color. This model does not include any of the 'reason for stop' variables as the FRISKED model did. This was because the addition of these models severely reduced the predictive ability of the model. Although with the addition of some of them it made AIC lower and all variables were significant, it gave a AOC value of less than 0.50, indicating that the model was worse than just taking a random guess. Omitting these variables still did not leave us with a great predictive model, with an AOC value of 0.5005, but we choose this model because it surpased the 0.50 threshold.

## LASSO Regression

LASSO regression was used to determine if machine learning could build a model that can make better predictions. Observations with missing data was removed, testing and training datasets were created, and cross validation was used to select the best model using the LASSO procedure. A matrix dataset was used to create dummy variables for all categorical variables, resulting in 33 variables. The lasso procedure for the FRISKED model only minimized one variable to zero and kept 32 variables in the model. The AUC value was 0.5403, which was less than the value selected from our logistic modeling. 
Based on the logistic model, only demopgrahics, characteristics, and location of stop were included in the 22 variable matrix. LASSO regression selected 10 of the 22 variables and minimized the others to 0. The resulting AUC value was 0.50, which was approximatley the same compared to the logistic model from above. 

# Additional Analysis

Additional analysis was performed for stopped individuals under age of 18. Reasons for stopping underaged kids are consistent with the overall trend in the data set. The most common reasons are "fits a relevant description", "furtive movements" and the "other". In 2016 80% of children stopped were innocent and 20% were arrested. Out of children who have been arrested 86% were black or Hispanic. 
*If you undertake formal statistical analyses, describe these in detail*


# Discussion
*What were you findings? Are they what you expected? What insights into the data can you make?*

The models created for FRISKED and ARST_MADE were not successful at predicting who would be frisked or arrested. These models were only slightly more sucessful at predicting whether or not the person would be frisked or arrested than taking a guess. While we were hoping to make a good predictive model, this points to the fact that officers are not basing their decisions on characteristics, demographics, and location of the stop. After the tactic came under scrutiny, the NYPD is taking measures to ensure that the policy is non-discriminant, which from our analyses we can see is successful. 



  


